// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://indrxksnzivinopjnhws.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImluZHJ4a3Nueml2aW5vcGpuaHdzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyODc4NTgsImV4cCI6MjA2Njg2Mzg1OH0.Ok3EeBjx3qIR9pnakUCQrWruUqsfQtzNg-SQq8F06JQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});